### GENERAL VARIABLES ###

PAIRED_END: FALSE


### INPUT FILES ###

# Complete this field if the sequencing is in Single_End AND the raw fastq files is multiplexed, if not leave blank: ""
# File extension format: .fastq.gz 
FASTQ: "RAWDATA/DEV.fastq.gz"

# Complete these two fields if the sequencing is in Paired_End AND the raw fastq files are multiplexed, if not leave blank: ""
# File extension format: _R1.fastq.gz and _R2.fastq.gz
FASTQ_R1: ""
FASTQ_R2: ""

# Complete this field if the raw fastq files are demultiplexed (sequencing Single_end or paired_end), if not leave blank: ""
# File extension format: PairedEnd > sampleX.R1.fastq.gz and sampleX.R2.fastq.gz / SingleEnd > sampleX.fastq.gz 
DEMULT_DIR: ""

# Complete this field in all cases
ADAPT_FILE: "CONFIG/adapter_file_DEV.txt"

# Complete this field if the raw fastq files are multiplexed (sequencing Single_end or paired_end), if not leave blank: ""
BARCODE_FILE: "CONFIG/barcode_file_DEV.txt"


### DEMULTIPLEXING PARAMETERS ###

# Complete these three fields if the raw fastq files is multiplexed, if not leave blank: ""
DEMULT_CORES: 1 # Cutadapt parameter "--cores"
DEMULT_SUBSTITUTIONS: 0.1 # Cutadapt parameter "--substitutions"


### TRIMMING PARAMETERS ###
TRIMMING_CORES: 1 # Cutadapt parameter "--cores"
TRIMMING_QUAL: 30 # Cutadapt parameter "--quality_cutoff"
TRIMMING_MIN_LENGTH: 36 # Cutadapt parameter "--minimum_length"