__default__:
    pe: smp 1
    q: short.q
    N: DC.{rule}
    o: Logs_DataCleaningWorkflow/{rule}.$JOB_ID.out.txt
    e: Logs_DataCleaningWorkflow/{rule}.$JOB_ID.err.txt

Demultiplex_RawFastqs:
    pe: smp {threads}

Trimming_DemultFastqs:
    pe: smp {threads}
    o: Logs_DataCleaningWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_DataCleaningWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

