__default__:
    cpus-per-task: 1
    partition: agap_normal
    mem-per-cpu: 2G
    job-name: RM.{rule}
    output: Logs_ReadMappingWorkflow/{rule}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.%j.err.txt

Mapping_PairedEndFastqs:
    cpus-per-task: "{threads}"
    mem-per-cpu: 5G
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Mapping_SingleEndFastqs:
    cpus-per-task: "{threads}"
    mem-per-cpu: 5G
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Stats_Bams:
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

MarkDuplicates_Bams:
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Filter_Bams:
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt
    
Index_Bams:
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Extract_PairedEndReads:
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Remapping_PairedEndExtractedFastqs:
    cpus-per-task: "{threads}"
    mem-per-cpu: 5G
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Extract_SingleEndReads:
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Remapping_SingleEndExtractedFastqs:
    cpus-per-task: "{threads}"
    mem-per-cpu: 5G
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Stats_Subbams:
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Filter_Subbams:
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Index_Subbams:
    output: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt
