__default__:
    cpus-per-task: 1
    mem-per-cpu: 2G
    partition: agap_normal
    job-name: VC.{rule}
    output: Logs_VariantCallingWorkflow/{rule}.%j.out.txt
    error: Logs_VariantCallingWorkflow/{rule}.%j.err.txt
    
HaplotypeCaller:
    cpus-per-task: "{threads}"
    partition: agap_bigmem
    mem-per-cpu: 27G
    output: Logs_VariantCallingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_VariantCallingWorkflow/{rule}.{wildcards.base}.%j.err.txt

GenomicsDBImport:
    cpus-per-task: "{threads}"

Plot_GVCFVariablesHistograms:
    mem-per-cpu: 4G

Plot_GVCFDPBoxplot:
    mem-per-cpu: 4G
    
Plot_GVCFVariantsAlongGenome:
    mem-per-cpu: 4G