__default__:
    cpus-per-task: 1
    partition: agap_normal
    mem-per-cpu: 2G
    job-name: VF.{rule}
    output: Logs_VcfFilteringWorkflow/{rule}.%j.out.txt
    error: Logs_VcfFilteringWorkflow/{rule}.%j.err.txt

Plot_FinalVCFVariablesHistograms:
    mem-per-cpu: 4G
